<?php

namespace Container7pg5Ki9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KchBa5JService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kchBa5J' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kchBa5J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'rapport' => ['privates', '.errored..service_locator.kchBa5J.App\\Entity\\Rapport', NULL, 'Cannot autowire service ".service_locator.kchBa5J": it references class "App\\Entity\\Rapport" but no such service exists.'],
            'user' => ['privates', '.errored..service_locator.kchBa5J.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.kchBa5J": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'rapport' => 'App\\Entity\\Rapport',
            'user' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
