<?php

namespace Container7pg5Ki9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRapportTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\RapportType' shared autowired service.
     *
     * @return \App\Form\RapportType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/RapportType.php';

        return $container->privates['App\\Form\\RapportType'] = new \App\Form\RapportType();
    }
}
