<?php

namespace ContainerEhmM65g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordModificationTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\PasswordModificationType' shared autowired service.
     *
     * @return \App\Form\PasswordModificationType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/PasswordModificationType.php';

        return $container->privates['App\\Form\\PasswordModificationType'] = new \App\Form\PasswordModificationType();
    }
}
