<?php

namespace ContainerEhmM65g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRapportService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8PlN4nm.App\Entity\Rapport' shared service.
     *
     * @return \App\Entity\Rapport
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.8PlN4nm": it references class "App\\Entity\\Rapport" but no such service exists.');
    }
}
